version: '3.8'

services:
  backend:
    build: ./backend
    container_name: resumeiq-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - APP_JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - APP_JWT_EXPIRATION_MS=86400000
    networks:
      - resumeiq-network

  frontend:
    build: ./frontend
    container_name: resumeiq-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - resumeiq-network

networks:
  resumeiq-network:
    driver: bridge
